### ISSUE TITLE
UI not translated: QueueModeNext / QueueModeInstant

### ISSUE THREAD

**Issue by camegone** [JLChnToZ/VVMW#16] opened 2023-10-20 18:09 UTC
These texts seem to be not properly translated. Whatever I changed language, they remained the same.
![image](https://github.com/JLChnToZ/VVMW/assets/121595305/48a8936e-05e9-41c3-8f3c-41d9f03b08f4)
![image](https://github.com/JLChnToZ/VVMW/assets/121595305/614db355-1ee0-42d1-a1c3-9793ecc82cd2)

Tested on the demo world: https://vrchat.com/home/world/wrld_7239d09c-7b25-43a5-8ccd-502d986b016a

**Comment by JLChnToZ** [comment] 2023-10-21 07:30
Hello! It seems the problem is the player unable to find the newly added texts, as these texts are added in 1.0.10, did you changed or copied the language text to elsewhere before updating to latest version?

**Comment by camegone** [comment] 2023-10-21 16:56
No, I did not modify the string; it occurred on your world.
Installing the latest VPM package into a new project did not produce the issue.
I tried to reproduce the issue on my world, but I couldn't.

**Comment by JLChnToZ** [comment] 2023-10-21 17:04
Oh I see! I thought you are talking about problem occurred when you try importing it to your world.
It's fine, just a minor issue that I will fix it later.
But it does not related the asset provided on this repository, so I'll close this issue.
Thanks for informing me about this anyway.

**Closed by JLChnToZ** 2023-10-21 17:04 UTC
